# Generated by Django 5.0.3 on 2024-03-19 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('user_name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(verbose_name='data dodania komentarza')),
            ],
        ),
        migrations.CreateModel(
            name='DisabilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(max_length=250)),
                ('number_of_ratings', models.IntegerField()),
                ('id_comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('url_imge', models.URLField(max_length=250)),
                ('url_map_google', models.URLField(max_length=250)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
                ('disability_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disabilitytype')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rating')),
            ],
        ),
    ]
