# Generated by Django 5.0.3 on 2024-03-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='disabilitytype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DisabilityType', to='api.disabilitytype'),
            preserve_default=False,
        ),
    ]
