# Generated by Django 5.0.3 on 2024-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rating_disabilitytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='disabilitytype',
        ),
        migrations.RemoveField(
            model_name='place',
            name='disability_type_id',
        ),
        migrations.AddField(
            model_name='place',
            name='disability_type_id',
            field=models.ManyToManyField(related_name='places', to='api.disabilitytype'),
        ),
    ]
