# Generated by Django 5.0.3 on 2024-03-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rating_disabilitytype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='ratings_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.rating'),
            preserve_default=False,
        ),
    ]
