# Generated by Django 5.0.3 on 2024-03-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_place_ratings_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='url_imge',
            new_name='url_image',
        ),
        migrations.RemoveField(
            model_name='place',
            name='ratings_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.place'),
        ),
    ]
