# Generated by Django 5.0.3 on 2024-03-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_url_imge_place_url_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='type_place',
            field=models.IntegerField(choices=[(1, 'Urząd'), (2, 'Pub'), (3, 'Restauracja'), (4, 'Muzeum'), (5, 'Miejsce związane z kulturą')], default=1),
            preserve_default=False,
        ),
    ]
